### ISSUE TITLE
Reduce duplication in scripts to generate golang-crossbuild docker images

### ISSUE THREAD

**Issue by andrewkroh** [elastic/golang-crossbuild#24]
With templating of Dockerfiles we can drastically reduce the amount of duplication in the repo. There are directories for each Go version actively in use by beats. We can collapse this down to one set of Dockerfiles and use templates to populate the Go version number and download hash.

At the top level I'd like to have a table of the Go version we are maintaining images for, then build images based on that.

```yaml
go:
  - version: 1.12.7
     sha256: c3406388e721e913130d368a79dd134788dc8d112ddcff277fd2cd129db8a17c
  - version: 1.11.9
     sha256: d3406388e721e913130d368a79dd134788dc8d112ddcff277fd2cd129db8a17c
```

Another possible optimization would be to investigate if we can move the Go installation to a later stage in the build. Then all of the lower layers would be exactly the same (and shared and cached) which would speed up builds at the cost of not having the Go installation as a shared layer.
