### ISSUE TITLE
Add version for ppc64le

### ISSUE THREAD

**Issue by cpmoore** [elastic/golang-crossbuild#30]
Can we add a version of the builder for linux ppc64le?

**Comment by kuisathaverat** [comment]
docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-ppc supports ppc64 and ppc64le

```
linux:
  ppc64:
    CC:  powerpc64-linux-gnu-gcc-6
    CXX: powerpc64-linux-gnu-g++-6
  ppc64le:
    CC:  powerpc64le-linux-gnu-gcc
    CXX: powerpc64le-linux-gnu-g++
```
